input {
  journal {
    path => "/var/log/journal"
  }
}

filter {
  mutate {
    rename => {
      "container_name" => "container.name"
      "container_id_full" => "container.id"
      "_hostname" => "host.name"
    }
  }

  if [message] =~ /^\{.*/ {
    json {
      source => "message"
      target => "app"
    }
  }
  else {
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" } # Exemple pour du web
      tag_on_failure => ["_grokparsefailure_standard"]
    }
  }

  mutate {
    remove_field => [ "cursor", "_cap_effective", "_transport", "_systemd_slice", "_systemd_cgroup" ]
  }
}

output {
  elasticsearch {
    hosts => ["https://es01:9200"]
    index => "podman-logs-%{+YYYY.MM.dd}"
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
    ssl_enabled => true
    ssl_certificate_authorities => ["/usr/share/logstash/config/certs/ca/ca.crt"]
    ssl_verification_mode => "full"
  }
  stdout {
    codec => rubydebug
    id => "syslog-debug"
  }
}
