# Multiple pipelines configuration
- pipeline.id: syslog-pipeline
  path.config: "/usr/share/logstash/pipeline/syslog.conf"

- pipeline.id: file-pipeline
  path.config: "/usr/share/logstash/pipeline/file.conf"

# - pipeline.id: journald-pipeline
  # path.config: "/usr/share/logstash/pipeline/journald.conf"
