services:
  prometheus:
    image: quay.io/prometheus/prometheus:v3.8.1
    container_name: prometheus
    ports:
      - "9191:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:z
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml:z
    networks:
      - monitor_net
      - prom_net
      - ft
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.50'
        reservations:
          memory: 256M
          cpus: '0.10'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  alertmanager:
    image: quay.io/prometheus/alertmanager:v0.25.0
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:z
    networks:
      - prom_net
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.15'
        reservations:
          memory: 32M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9093/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "0"
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN}
      - GF_SECURITY_ADMIN_PASSWORD=${PASSW}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_CERT_FILE=/etc/grafana/certs/cert.pem
      - GF_SERVER_CERT_KEY=/etc/grafana/certs/key.pem
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:z
      - ./grafana/dashboards:/var/lib/grafana/dashboards:z
      - ../../cybersecurity/waf/certs:/etc/grafana/certs:z
    networks:
      - prom_net
      - ft
    deploy:
      resources:
        limits:
          memory: 384M
          cpus: '0.50'
        reservations:
          memory: 128M
          cpus: '0.10'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "--no-check-certificate", "https://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.10.2
    container_name: node_exporter
    restart: "no"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - prom_net
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.10'
        reservations:
          memory: 16M

networks:
  prom_net:
    driver: bridge
    name: prom_net
