export const RECIPE = {
	RECIPES: 'recipes',
	RECIPE: (id: string) => `recipes/${id}`,
	RECOMMENDED: 'recipes/recommended',
	ME_RECIPES: 'recipes/me',
	SEARCH: 'recipes/search',
	BY_SLUG: (slug: string) => `recipes/by-slug/${slug}`,
	FAVORITE: (id: string) => `recipes/${id}/favorite`,
	MY_FAVORITES: 'me/favorites',
	RATINGS: (id: string) => `recipes/${id}/ratings`,
	COMMENTS: (id: string) => `recipes/${id}/comments`,
	COMMENT: (recipeId: string, commentId: string) => `recipes/${recipeId}/comments/${commentId}`,
	REPLY: (recipeId: string, commentId: string) => `recipes/${recipeId}/comments/${commentId}/replies`,
	BY_CATEGORY: (categoryId: string) => `recipes/category/${categoryId}`,
	BY_AUTHOR: (authorId: string) => `recipes/author/${authorId}`,
	BY_DIFFICULTY: (difficulty: string) => `recipes/difficulty/${difficulty}`,
	SIMILAR: (id: string) => `recipes/${id}/similar`,
	CREATE: 'recipes',
	UPLOAD_IMAGE: (recipeId: string) => `recipes/${recipeId}/images/upload`,
	CATEGORIES: 'categories',
	DIETARY_TAGS: 'dietary-tags',
} as const;
