export const SOCIAL = {
	SEARCH_USERS: 'users/search',
	FOLLOW: (userId: string) => `users/${userId}/follow`,
	IS_FOLLOWING: (userId: string) => `users/${userId}/is-following`,
	MY_FOLLOWERS: 'users/me/followers',
	MY_FOLLOWING: 'users/me/following',
	USER_FOLLOWERS: (userId: string) => `users/${userId}/followers`,
	USER_FOLLOWING: (userId: string) => `users/${userId}/following`,
	SEND_FRIEND_REQUEST: 'users/friend-requests',
	MY_FRIEND_REQUESTS: 'users/me/friend-requests',
	MY_SENT_FRIEND_REQUESTS: 'users/me/friend-requests/sent',
	ACCEPT_FRIEND_REQUEST: (requestId: string) => `users/friend-requests/${requestId}/accept`,
	REJECT_FRIEND_REQUEST: (requestId: string) => `users/friend-requests/${requestId}/reject`,
	CANCEL_FRIEND_REQUEST: (requestId: string) => `users/friend-requests/${requestId}/cancel`,
	MY_FRIENDS: 'users/me/friends',
	REMOVE_FRIEND: (friendId: string) => `users/friends/${friendId}`,
	BLOCK: (userId: string) => `users/${userId}/block`,
	BLOCKED_USERS: 'users/me/blocked',
} as const;
