export enum NotificationType {
    NEW_FOLLOWER = 'NEW_FOLLOWER',
    NEW_FRIEND_REQUEST = 'NEW_FRIEND_REQUEST',
    FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED',
    FRIEND_REQUEST_REJECTED = 'FRIEND_REQUEST_REJECTED',
    NEW_COMMENT = 'NEW_COMMENT',
    NEW_RATING = 'NEW_RATING',
    NEW_MESSAGE = 'NEW_MESSAGE',
    RECIPE_FAVORITED = 'RECIPE_FAVORITED',
    NEW_RECIPE = 'NEW_RECIPE'
}
